---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mysql-root-password
  namespace: default
spec:
  encryptedData:
    root-password: AgB91EClSy6e2PHfVNVbTCmBSeZRawvjWeDq66sHZ9V+DquQYY+iDoUn8wa17+Zi03eOSmFNI6S3R1Wk/xQOMSPhZXwng/SE1T0QUvVsP+EbPJL00EDD2qw0tkfoyVW9GviXQlz4Ljo1vx5WTj/MVywiPHpJJaqWanukYhNjSBqTHHFMBUuOMhPnwzJ9ikNflwnhL8mxvmaxrqYIqghh+Om99Knw7OMo38s/M4bDFMtYbJc4FKL2LP5G0mu/rHv7qXCLTQGbJTxU8hAT0OFwGtZTkmLBcyWr+NPp4TjTlP5jEb5k6BCDp+scmBxCLqDNMr/owe1I8XYVlj4pxAVQ+Xl26miGCCSBNaV8FNJ8wfcsme5OdsO0DKBVYv73M+y61w2kwXlgIw1EHkBAGmU9oVEFZiKOPMqoFYSX+qaqw3RvOsKsVoUU0X4C/HRyEQirDpPetTmSfriBphzc+/lN+YQE2BOGSoB2tJkDyCvTynU3WDGyf4Vwd5wr3/BvEFFf2xk4yH0/S0t2PxmLXhKqBf3aubtvSLzfWhOzPspncEtjg52M0sMCt47HwivGVcoPre4lZPcS4ExT5vvU6NvwteKfR5XXYx9rxAyBCRc/jLRAxY9xizzXQotvSe0+1Eh5rpMqvBg8AnTTModKlyqRidJRI4KUbcD8iXlYvSug2jtLYLxq+36IpJzNUez2nHqTEJozgN4/EvnxENKkrbnWW/gdpd8=
  template:
    metadata:
      creationTimestamp: null
      name: mysql-root-password
      namespace: default
