---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: minio-secrets
  namespace: minio
spec:
  encryptedData:
    rootPassword: AgBoSk+4Oi9vbDqmHwb8HX/4TZIwjgcsrAxIHmk7l/SbuHML8BYcwO+JYrtjTuuHQ6/bWYZ4ce4cHiKyHWKEm3eLdAqOaFE5VTjH0C147PvkLxu5Bx4MMQUGZP7cQaxCZVFf2VDSkkpSoGraPKVhNlCMCsxf41b034rhmpcVpjZRYods2aioSanKE4VtDVEZJlvFm04pJBfhzZ9p+wVwuBWJn+1GwOSY3nkIzDHkuuudJOslhJ3sdfUGArvisl4n4tzodFyw3kmUTDO6v+ViV/jmT+GfmetYSqgBW01ZVIfYKeIwzti5Ju4sEVowN6aDtCEOeo3WQN8w6jiPvqoXqR8St6JzQm7EvnY34s9mtBA3HLwO5AJGXKFVsRzFSt0lIVMAA6VVxHwnSev9brf2RrmIxa2DFA2lDm0RxuiyT0weUa4R+A1EhSSb0ZTy0BgWI631cB7jX/0/Tj2y3+/R/nFhGfezTFUxEyc6LKGvhjyEL4gmUGUIu/bHRU61qi1BUW/0xRvv0HO2devexwzH4jXJWoWnN7yOt/dfXocgseSlrld1ReLdjH76j/32DzhbeNK6n1c9TiunmbLOe8b8khpGnHrAGL3UeklTuSmefTGttUhOd16hIZfLm+n1AbQa6VNYSJ29sQ1OaUQBZ+74bTjZMe3OzdwK4XvuLTXyZCDvhp6G0s5Wwb7wpU7E9ERb/bf7pcNq8hQvqV76HwWd1r8d+w==
    rootUser: AgBrPWaeRJeTfR71hhl+wkOBDEbC34QIM2uHYXZnLHd8IeVUKTs5ARBOlpf1TLXXclfeX0s2IToJYw+CfImG3KXTbkrkXg3e2sTS6fWNVYbvjqwMZWawC6De4y/tNUdHzNA5QsNQ83dc+K6pEsBCHkb4ChVphPhQKhWMN9jJYOUGuYf1crYJiAXhh05AYzSFtht7/Hl2BLlFrMncVxhzDvZmPHyemVTvehsFKaM3qy/fN/nD1qwyoWumfrtWB7S6mn+fvIydFyg893pI1J0ugXIrDeHWqOr46s69JqTIrH+7D/za79S84ymS3d2OROPFRuzHyFAbmixYIKPLAZMf0fTr4+iuQ2eP9t12Uk2LqpFj9M7SZ9UbnfsBAoJFqsTIXyc6anczObgoGCQUnu2oO3kfFZ4eX5Exqld8UnGo11pG6XfMYHZZwuZWUpYuuPYa/aFfdfD4elfbNAKCysXvDCYV1J0Qzu8JrtiTyVXV55ZeDICcwtwT5GeLgLaYATvsmHQ+eHnb/U8XQtV7jQxSGf6pDEpCLDsdSz4Tx7tB1Kz3bFz81OGD3w/pS3RkCeeHKhYgIKTk3uhxxxTpvR7aYkxvI1yymFXnehfWj8bkJBfTM0Lm99x5i9ocQFLNrhETKdlLDZzzdRLDtNPsFf5SsrWKTtIgjIxPNzkWaUea9PJigMc2knNhRB00UDNPI1ip9fHwGiCNkg==
  template:
    metadata:
      creationTimestamp: null
      name: minio-secrets
      namespace: minio
