spring:
  threads:
    virtual:
      enabled: true
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:notes}?useUnicode=yes&allowPublicKeyRetrieval=true&useSSL=false&characterEncoding=UTF-8
    username: ${DB_USER:root}
    password: ${DB_PASS:root}
    hikari:
      maximum-pool-size: ${DB_MAX_POOL_SIZE:5}
      minimum-idle: ${DB_MIN_POOL_SIZE:2}
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
joinfaces:
  faces:
    project-stage: development
  primefaces:
    theme: saga

