name: Deploy

on: workflow_dispatch

jobs:
  build-and-deploy:
    runs-on: [self-hosted, linux]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'temurin'
          cache: 'maven'
          check-latest: true

      - name: Set up Maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: 3.9.2

      - name: Build with Maven
        run: mvn clean package
        working-directory: ./notebook

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry (with PAT)
        run: echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u trubent --password-stdin

      - name: Build and push Docker image
        run: |
          IMAGE_NAME=ghcr.io/${{ github.repository_owner }}/ruben-notes:latest
          docker build -t $IMAGE_NAME ./notebook
          docker push $IMAGE_NAME

      - name: Helm deploy to k3s
        run: |
          helm upgrade --install ruben-notes ./helm \
            --set image.repository=ghcr.io/${{ github.repository_owner }}/ruben-notes \
            --set image.tag=latest
