name: Test Runner

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test-runner:
    runs-on: self-hosted  # This makes it run on your k3s node

    steps:
      - name: Check Runner
        run: echo "Runner is working!"
